# name: Scan

# on: [push]

# permissions: read-all

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4
#       - name: Run Checkov action
#         id: checkov
#         uses: bridgecrewio/checkov-action@v12
#         with:
#           directory: .
#           framework: terraform
